name: health_wellbeing_app
description: "Health and Wellbeing App in Flutter, Dart, Firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.4.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.3.1
  geocoding: ^2.1.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  rxdart: ^0.27.7
  intl: ^0.19.0
  shared_preferences: ^2.2.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/AppLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/AppLogoText.png
    - assets/images/AppLogo.png
    - assets/images/cardiogram.png
    - assets/images/dots.png
    - assets/images/exercise.png
    - assets/images/productivity.png
    - assets/images/emma.webp
    - assets/images/gift.png
    - assets/images/group-users.png
    - assets/images/happy.jpg
    - assets/images/healthymeals.jpg
    - assets/images/home.png
    - assets/images/meditation.png
    - assets/images/mind.webp
    - assets/images/mindmentalhealth.png
    - assets/images/motivation.jpg
    - assets/images/runningchallenge.jpg
    - assets/images/sleeptracker.png
    - assets/images/virtualevents.png
    - assets/images/education.png
    - assets/images/cardiogram_faded.png
    - assets/images/education_faded.png
    - assets/images/gift_faded.png
    - assets/images/group-users_faded.png
    - assets/images/home_faded.png
    - assets/images/loginbg.png
    - assets/images/changepasswordbg.png
    - assets/images/goalsbg.png
    - assets/images/personalinfobg.png
    - assets/images/profilebg.png
    - assets/images/userdetailsbg.png
    - assets/images/APPICON.png
    - assets/images/morningroutine.webp
    - assets/images/fitnessandyou.jpg
    - assets/images/dailywellness.png
    - assets/images/mindfullness.png
    - assets/images/handlingstress.png
    - assets/images/powerofrest.jpg
    - assets/images/healthyfoodtips.jpg
    - assets/images/superfoods.jpg
    - assets/images/portioncontrol.webp
    - assets/images/quotebg1.jpg
    - assets/images/quotebg2.jpg
    - assets/images/quotebg3.jpg
    - assets/images/quotebg4.jpg
    - assets/images/registerbg2.png
    - assets/images/registerbg.jpg
    - assets/images/createevent.png
    - assets/images/nutrition.png
